#!/bin/bash

# Unlink previously linked versions. Fixes a harmless error message that may
#  cause issues down the line.

for variant in '' '-dark' '-light' '-slim' '-dark-slim' '-light-slim'; do
    for version in '3.20' '3.22'; do
        assets="/usr/share/themes/Pop$variant/gtk-$version/assets"
        if [ -L "$assets" ]; then
            unlink "$assets"
        fi
    done
done
